<a id="inicio"></a>
<br><br><br>
<div align="left">
<h1><font size=6>Pandas</font></h1>
    <h2><font color="#5E5E5E" size=5>12. Categorías</font>  </h2>
<br><br><br><br>
</div>


<div align="right">
<font color="#B51700" size=4><b>Análisis y visualización de datos</b></font><br><br>
<font  size=3>Máster Universitario en Ingeniería Informática</font><br>
<font  size=3>Máster Universitario en Big Data y Computación en la Nube</font><br>
<font size=3>Máster Universitario en Inteligencia Artificial</font><br><br>
<font color="#5E5E5E" size=3><b>Luis de la Ossa  &nbsp;&nbsp;</b></font><span style="background-color:#B51700; color:white; padding:2px 6px; font-family:Arial, sans-serif;font-weight:bold;font-size:18px;">UCLM</span>
</div>

In [1]:
import pandas as pd

import warnings  
warnings.filterwarnings('ignore')   # Se silencian algunos warnings

---

## <font color="#5E5E5E">1. Introducción</font>

En una libreta anterior se ha discretizado el valor de la columna `df_titanic['Tarifa']` mediante las funciones `pd.cut()` y `pd.qcut()`. Al mostrar las `Series` resultantes pueden observarse dos circunstancias.

In [2]:
df_titanic = pd.read_csv('data/titanic_prep.csv', index_col=0)
df_titanic.head()

,Sobrevive,Clase,Nombre,Sexo,Edad,Esposa/Hermanos,Padres/Hijos,Ticket,Tarifa,Número de Cabina,Puerto
Pasajero,,,,,,,,,,,
1,No,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,Yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,Yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,Yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,No,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df_titanic['Tarifa disc'] = pd.qcut(df_titanic['Tarifa'],3, labels=['Barata', 'Media', 'Cara'])
df_titanic['Tarifa disc'].head()

Pasajero
1    Barata
2      Cara
3    Barata
4      Cara
5    Barata
Name: Tarifa disc, dtype: category
Categories (3, str): ['Barata' < 'Media' < 'Cara']

En primer lugar, el tipo de la serie es `category`, e incluye el número y conjunto de valores que puede tomar. Por otra parte, se establece una relación de orden entre ese conjunto de valores.

_pandas_ implementa un tipo de datos específico para el trabajo con datos categóricos, es decir, ___variables que pueden tomar un número finito y determinado de valores___. Aunque estos valores se visualizan como `strings`, _internamente se representan mediante enteros_, lo que permite un tratamiento eficiente. El uso de series/columnas con valores categóricos, aporta tres ventajas:

1. No se pueden asignar a los elementos valores que no estén recogidos en las categorías. Esto repercute en control sobre la integridad de los datos, y evita fallos.

In [ ]:
# df_titanic.loc[100, 'Tarifa disc']='Muy cara' # Produce un error

2. En segundo lugar, se define una relación de orden entre los valores. Se pueden utilizar operaciones de comparación para, por ejemplo seleccionar datos.

In [4]:
df_titanic[df_titanic['Tarifa disc']>'Media']

,Sobrevive,Clase,Nombre,Sexo,Edad,Esposa/Hermanos,Padres/Hijos,Ticket,Tarifa,Número de Cabina,Puerto,Tarifa disc
Pasajero,,,,,,,,,,,,
2,Yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cara
4,Yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Cara
7,No,first,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Cara
10,Yes,second,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Cara
12,Yes,first,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Cara
...,...,...,...,...,...,...,...,...,...,...,...,...
872,Yes,first,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,Cara
880,Yes,first,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Cara
886,No,third,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q,Cara
888,Yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Cara
890,Yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Cara

3. Por último, la representación categórica ocupa menos espacio en memoria que la representación equivalente en formato `string`.

In [5]:
df_titanic['Tarifa str'] = df_titanic['Tarifa disc'].astype(str)
df_titanic.memory_usage(deep=True)

Index                 132
Sobrevive           45783
Clase               48298
Nombre              67685
Sexo                47851
Edad                 7128
Esposa/Hermanos      7128
Padres/Hijos         7128
Ticket              49674
Tarifa               7128
Número de Cabina    32712
Puerto              44514
Tarifa disc          1161
Tarifa str          48127
dtype: int64

---

## <font color="#5E5E5E"><i class="fa fa-plus-circle" aria-hidden="true" style="color:#5E5E5E"></i> 2. El tipo de objetos `Categorical`</font>


Los objetos de tipo `pd.Categorical` permiten representar __una colección__ (no un `series`) de datos categóricos. Por defecto, si se contruye a partir de una lista de `strings`, considera tantas categorías como detecta en los datos, pero éstas se pueden especificar mediante el argumento `categories`.

In [6]:
pd.Categorical(["primera","segunda","tercera","primera", "tercera", "especial"])

['primera', 'segunda', 'tercera', 'primera', 'tercera', 'especial']
Categories (4, str): ['especial', 'primera', 'segunda', 'tercera']

In [7]:
# Solo considera tres categorías. 
pd.Categorical(["primera","segunda","tercera","primera", "tercera", "especial"],
                categories=["primera","segunda","especial"])

['primera', 'segunda', NaN, 'primera', NaN, 'especial']
Categories (3, str): ['primera', 'segunda', 'especial']

<div class="alert alert-block alert-info">

<i class="fa fa-info-circle" aria-hidden="true"></i> En una colección de valores categóricos, aquellos cuya categoría no ha sido especificada se codifican como `np.NaN`.
</div>

También es posible ___establecer una relación de orden___ entre las categorías.

In [8]:
pd.Categorical(["primera","segunda","tercera","primera", "tercera", "especial"],
                categories=["primera","segunda","especial"], ordered=True)       # "tercera" no existe.

['primera', 'segunda', NaN, 'primera', NaN, 'especial']
Categories (3, str): ['primera' < 'segunda' < 'especial']

### <font color="#5E5E5E"> El tipo  `CategoricalDType` </font></font>

Un tipo de datos categórico se representa mediante `CategoricalDType`, y permite definir dos aspectos:

1. `categories`: El conjunto de valores categóricos.
2. `ordered`: Un valor booleano que representa si se establece un orden o no entre los valores categóricos.

In [10]:
from pandas.api.types import CategoricalDtype

tipo_calidades = CategoricalDtype(categories=["primera","segunda","especial"], ordered=True)

Es posible construir una secuencia de valores categóricos pasando como parámetro un objeto de tipo `CategoricalDtype` a través del parámetro `dtype`.

In [11]:
# Esto es equivalente a la construcción anterior.
pd.Categorical(["primera","segunda","tercera","primera", "tercera", "especial"], dtype=tipo_calidades)

['primera', 'segunda', NaN, 'primera', NaN, 'especial']
Categories (3, str): ['primera' < 'segunda' < 'especial']

Tanto las categorías como el orden utilizados en un objeto `Categorical` pueden accederse a través de `Categorical.categories` y `Categorical.ordered`.

In [12]:
calidades = pd.Categorical(["primera","segunda","tercera","primera", "tercera", "especial"], dtype=tipo_calidades)
print(calidades.categories)
print(calidades.ordered)

Index(['primera', 'segunda', 'especial'], dtype='str')
True

<div class="alert alert-block alert-warning">

<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
En este punto es importante distinguir entre `CategoricalDtype` que permite definir los valores que puede tomar una categoría, y el objeto `Cagorical` que contiene una secuencia de valores del tipo `CategoricalDtype`.
</div>

### <font color="#5E5E5E"> Renombrado de categorías</font>

Es posible renombrar las distintas categorías consideradas en un objeto `Categorical`  mediante el método `Categorical.rename_categories()`. Éste puede tomar como argumentos una lista, o un diccionario. La operación redefine tanto el tipo de datos (etiquetas de las categorías) como los valores almacenados, y produce un nuevo objeto `Categorical`.

In [ ]:
calidades.rename_categories(['1ª','2ª','Extra'])   # Reemplaza los valores

In [ ]:
calidades.rename_categories({'segunda':'2ª',
                             'especial':'Extra',
                             'primera':'1ª'})                      # Los vuelve a reemplazar.

### <font color="#5E5E5E"> Reemplazo de categorías</font>

El método `Categorical.set_categories()` permite reestablecer las categorías. Su aplicación devuelve un nuevo objeto de tipo `Categorical`. Si alguna categoría desaparece, los valores correspondientes pasan a ser `np.NaN`.

In [ ]:
calidades.set_categories(['primera','segunda'])

### <font color="#5E5E5E"> Adición de categorías</font>

Es posible añadir nuevas categorías mediante el método `Categorical.add_categories()`.

In [ ]:
calidades = calidades.add_categories(['tercera','superior'])
calidades

<div class="alert alert-block alert-warning">

<i class="fa fa-exclamation-circle" aria-hidden="true"></i> Los valores `NaN` siguen siendo `NaN` tras aplicar las dos funciones anteriores.
</div>

### <font color="#5E5E5E"> Eliminación de categorías</font>

El método `Categorical.remove_categories()` permite eliminar categorías.

In [ ]:
calidades = calidades.remove_categories(['superior'])
calidades

Además, existe un método, denominado `Categorical.remove_unused_categories()` que permite eliminar las categorías que no han sido utilizadas.

In [ ]:
calidades = calidades.remove_unused_categories() # Elimina la categoría superextra
calidades

### <font color="#5E5E5E"> Gestión del orden </font>

Los métodos `Categorical.as_ordered()` y `Categorical.as_unordered()` permiten, respectivamente, establecer o eliminar el orden establecido entre las etiquetas.

In [ ]:
calidades.as_unordered()

El método `Categorical.reorder_categories()` permite cambiar el orden de las categorías.

In [ ]:
calidades.reorder_categories(["segunda", "especial", "primera"], ordered=True)

### <font color="#5E5E5E"> Unión de conjuntos de datos categóricos </font>

`union_categoricals()` concatena los valores de varios objetos categóricos y construye un conjunto de categorías que incluye las etiquetas de todos ellos. En este ejemplo ambos objetos son no ordenados y sus categorías no se solapan.

In [ ]:
from pandas.api.types import union_categoricals

calidades1 = pd.Categorical(["Limón", "Naranja", "Naranja", "Limón"])
calidades2 = pd.Categorical(["Melón", "Sandía", "Sandía", "Melón"])

union_categoricals([calidades1, calidades2])

---
## <font color="#5E5E5E">3. Series con valores categóricos </font>

Se puede crear un objeto `Series` de valores categóricos directamente especificando (a través de `dtype`) el tipo `category`. En ellos, los valores (`Series.values`) son un objeto de tipo `Categorical`.

In [ ]:
# Crea una serie con valores de tipo category
pd.Series(["primera","segunda","tercera","primera", "tercera", "especial"], dtype="category")

Si no se especifica el tipo, las etiquetas se consideran `str`, pero se puede convertir mediante `Series.astype()`.

In [ ]:
# Crea una serie de valores de tipo String
pd.Series(["primera","segunda","tercera","primera", "tercera", "especial"])

In [ ]:
# Convierte la serie a valores de tipo category
calidades.astype("category")

También es posible crear la serie pasando como tipo un objeto  `CategoricalDtype`.

In [13]:
tipo_calidades = CategoricalDtype(categories=["primera", "segunda", "tercera", "especial"], ordered=True)
calidades = pd.Series(["primera","segunda","tercera","primera", "tercera", "especial"], dtype=tipo_calidades)
calidades

0     primera
1     segunda
2     tercera
3     primera
4     tercera
5    especial
dtype: category
Categories (4, str): ['primera' < 'segunda' < 'tercera' < 'especial']

Las funciones de agregación se adaptan al trabajo con categorías.

In [14]:
calidades.min()
calidades.mode()

0    primera
1    tercera
dtype: category
Categories (4, str): ['primera' < 'segunda' < 'tercera' < 'especial']

In [15]:
calidades.value_counts()

primera     2
tercera     2
segunda     1
especial    1
Name: count, dtype: int64

También es posible utilizar los accesores `str` y `dt` (se verá después) si las etiquetas son compatibles.

In [16]:
calidades.str.upper()

0     PRIMERA
1     SEGUNDA
2     TERCERA
3     PRIMERA
4     TERCERA
5    ESPECIAL
dtype: object

### <font color="#5E5E5E"> Manipulación de las categorías en Series</font>

`Series.cat` proporciona acceso a todas las funciones descritas para `Categorical`.


<div class="alert alert-block alert-info">

<i class="fa fa-info-circle" aria-hidden="true"></i> Las funciones que proporciona el objeto `Categorical` que contiene los valores del `Series` se __deben acceder__ a través de la propiedad `Series.cat`. 
</div>

In [17]:
print(calidades.cat.categories)
print(calidades.cat.ordered)
#print(calidades.cat)
#print(calidades.values)
#print(calidades.cat.codes)

Index(['primera', 'segunda', 'tercera', 'especial'], dtype='str')
True

#### <font color="#5E5E5E"> Renombrado de categorías</font>

In [ ]:
calidades = calidades.cat.rename_categories(['1ª','2ª','3ª','Extra'])
# calidades.cat.categories = ['1ª','2ª','3º','Extra']     # Equivalente
calidades

In [ ]:
# También puede tomar un diccionario
calidades = calidades.cat.rename_categories({'1ª':'primera',
                                             '2ª':'segunda',
                                             '3ª':'tercera',
                                             'Extra':'especial'})
calidades

#### <font color="#5E5E5E"> Reemplazo de categorías</font>

In [ ]:
calidades = calidades.cat.set_categories(["primera", "segunda", "tercera", "extra"], ordered=True)
calidades # Extra no existía

#### <font color="#5E5E5E"> Adición y eliminación </font>

In [ ]:
# Añade una categoría
calidades = calidades.cat.add_categories(["especial"])
calidades

In [ ]:
# Elimina la categoría
calidades = calidades.cat.remove_categories(["especial"])
print(calidades)

#### <font color="#5E5E5E"> Eliminación de categorías no utilizadas </font>

In [ ]:
calidades = calidades.cat.remove_unused_categories()
calidades

#### <font color="#5E5E5E"> Reordenación </font>

In [ ]:
# Elimina el orden
calidades = calidades.cat.as_unordered()
calidades

In [ ]:
# Vuelve a usar el orden (no determina cual)
calidades.cat.as_ordered()

In [ ]:
# Determina el orden
calidades.cat.reorder_categories(["segunda","primera","tercera"], ordered=True)

### <font color="#5E5E5E"> Ordenación según categorías</font>

Es posible ordenar los *Series* en función de las etiquetas mediante `Series.sort_values()`.

In [ ]:
tipo_calidades = CategoricalDtype(categories=["primera","segunda","especial"], ordered=True)
calidades = pd.Series(["primera","segunda","tercera","primera", "tercera", "especial"], dtype=tipo_calidades)

In [ ]:
calidades.sort_values(inplace=False)

---
### <font color="#5E5E5E"> Operaciones con Series de valores categóricos.</font>
<br>

Es posible llevar a cabo operaciones de comparación entre `Series` de datos categóricos **cuando utilizan la misma categoría**.

In [ ]:
tipo_calidades = CategoricalDtype(categories=["segunda","primera","especial"], ordered=True)

calidades1 = pd.Series(["primera","segunda","tercera","especial", "tercera", "especial"], dtype=tipo_calidades)
calidades2 = pd.Series(["segunda","segunda","segunda","primera", "especial", "especial"], dtype=tipo_calidades)

print(calidades1>calidades2)
#print(calidades1==calidades2)
#print(calidades1>"primera")

---
## <font color="#5E5E5E"><i class="fa fa-plus-circle" aria-hidden="true" style="color:#5E5E5E"></i> 4. Indexación con valores categóricos.</font>


También es posible utilizar valores categóricos en el índice de las `Series`.

In [18]:
niveles = pd.Categorical(
    ["Bajo", "Muy alto", "Medio", "Alto"],
    categories=["Bajo", "Medio", "Alto", "Muy alto"],
    ordered=True
)

df_clientes = pd.DataFrame({
    "satisfaccion": niveles,
    "numero_clientes": [15, 68, 31, 42]
}).set_index("satisfaccion")

df_clientes

              numero_clientes
satisfaccion
Bajo                       15
Muy alto                   68
Medio                      31
Alto                       42

In [19]:
# Índice y uso del índice
print(type(df_clientes.index),'\n')
print(df_clientes.loc["Alto"],'\n')

<class 'pandas.CategoricalIndex'>

numero_clientes    42
Name: Alto, dtype: int64

 La indexación por categorías permite también cierto grado de _slicing_. Las etiquetas utilizadas deben ser únicas.

In [20]:
# Slicing
df_clientes.sort_index()["Bajo":"Alto"]

              numero_clientes
satisfaccion
Bajo                       15
Medio                      31
Alto                       42

<br>
<div align="right">
<a href="#inicio"><font size=5 color="#B51700"><i class="fa fa-arrow-circle-up" aria-hidden="true"></i></font></a>
</div>

---

<div align="right">
<font size=5 color="#B51700"><i class="fa fa-coffee" aria-hidden="true"></i></font>
</div>